name: Marvin Tests with Codecov

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build and test with Maven
      run: mvn clean verify

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: target/site/jacoco/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }}  # Add this in GitHub Secrets
